name: Frontend Continuous Integration

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Restore npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('C:\balram0179git\bal-udacity-learning\starter\frontend\package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Navigate to the frontend directory
        run: cd C:\balram0179git\bal-udacity-learning\starter\frontend && pwd

      - name: Install dependencies
        run: |
          cd /starter/frontend
          npm ci

      - name: Run lint
        run: |
          cd /starter/frontend
          npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Restore npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('workspace/starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd workspace/starter/frontend
          npm ci

      - name: Run tests
        run: |
          cd workspace/starter/frontend
          npm run test

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Restore npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('/starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd workspace/starter/frontend
          npm ci

      - name: Build Docker image
        run: |
          cd workspace/starter/frontend
          docker build -t frontend-application .
